Added new button component
Aejnor/randomName pull request #3
Opened 2020-09-08 06:36 UTC by Aejnor

- Added new component
- Readme edited

2020-09-08 07:30 UTC, IvanCoronado requested changes

2020-09-08 07:30 UTC, IvanCoronado commented on src/components/Button/stories.tsx
> +      icon= { iconPosition && <FakeIcon /> }
Esto no está pasando por el prettier, comprueba que lo tienes bien configurado.

2020-09-08 07:30 UTC, IvanCoronado commented on storybook-static/asset-manifest.json
> +{
el storybook-static qué es? No hace falta subirlo al repo

2020-09-08 07:30 UTC, IvanCoronado commented on storybook-static/iframe.html
> +<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Storybook</title><meta name="viewport" content="width=device-width,initial-scale=1"><base target="_parent"><style>:not(.sb-show-main)
ni eso

2020-09-08 07:30 UTC, IvanCoronado commented on storybook-static/index.html
> +<!doctype html><html lang="en"><head><meta charset="utf-8"/><title>Storybook</title><meta name="viewport" content="width=device-width,initial-scale=1"/><style>html, body {
ni esto

2020-09-08 07:30 UTC, IvanCoronado commented on storybook-static/manifest.json
> +{
ni nada de lo que esté en esta carpeta

2020-09-08 09:21 UTC, Aejnor commented on storybook-static/manifest.json
> +{
Ya esta borrada la carpeta de storybook-static del repo y corriendo en netlify

2020-09-08 09:21 UTC, Aejnor commented on src/components/Button/stories.tsx
> +      icon= { iconPosition && <FakeIcon /> }
Ya esta pasado lo del prettier

2020-09-09 08:15 UTC, IvanCoronado requested changes

2020-09-09 08:15 UTC, IvanCoronado commented on commitlint.config.js
> +                ...readSubDirs('src/components/Button'),
El Button no hace falta añadirlo. Con poner 'src/components' ya tienes acceso a todos las carpetas que cuelga de components

2020-09-09 08:15 UTC, IvanCoronado commented on commitlint.config.js
> +                ...readSubDirs('src/containers/Guest'),
el Guest y el Main si están bien añadidos porque así puedes usar el nombre de carpetas que haya dentro.

2020-09-09 09:27 UTC, merged